task_templates:
- &install-deps
  task: install-dependencies
  file: concourse/tasks/install-deps.yml
  timeout: 30m
- &test-code
  task: run-unit-tests
  input_mapping:
    code-base: code-with-dependencies
  params:
    CODECOV_TOKEN: ((codecov-token))
  file: concourse/tasks/unit-tests.yml
  timeout: 1h
- &build-linux
  task: build-linux
  file: concourse/tasks/build.yml
  timeout: 1h
  input_mapping:
    code-base: code-with-dependencies
  params:
    TC_HELP_DESK_TOKEN: ((help-desk-token))
    TC_HELP_DESK_EMAIL: ((help-desk-email))
    PLATFORM: linux
  on_success:
    do:
    - put: upload
      # params:
      #   file: build/linux/*
      #   acl: public-read
- &build-macos
  task: build-macos
  file: concourse/tasks/build.yml
  timeout: 1h
  input_mapping:
    code-base: code-with-dependencies
  params:
    TC_HELP_DESK_TOKEN: ((help-desk-token))
    TC_HELP_DESK_EMAIL: ((help-desk-email))
    PLATFORM: macos
  on_success:
    do:
    - put: upload
      # params:
      #   file: build/macos/*
      #   acl: public-read
- &build-windows
  task: build-windows
  file: concourse/tasks/build.yml
  timeout: 1h
  input_mapping:
    code-base: code-with-dependencies
  params:
    TC_HELP_DESK_TOKEN: ((help-desk-token))
    TC_HELP_DESK_EMAIL: ((help-desk-email))
    PLATFORM: windows
  on_success:
    do:
    - put: upload
      # params:
      #   file: build/windows/x64/*
      #   acl: public-read
    # - put: upload
      # params:
      #   file: build/windows/x32/*
      #   acl: public-read

groups:
- name: develop
  jobs:
  - test-develop
  - build-develop
- name: pull requests
  jobs:
  - test-pr
  - build-pr
- name: releases
  jobs:
  - test-release
  - build-release

resource_types:
- name: git-branch-heads
  type: docker-image
  source:
    repository: vito/git-branch-heads-resource
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: s3-folder
  type: docker-image
  source:
    repository: neutrinog/s3-resource-simple

resources:
- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook))
- name: develop-branch
  type: git
  source:
    uri: https://github.com/unfoldingWord-dev/translationCore
    branch: develop
- name: release-branch
  type: git-branch-heads
  source:
    uri: https://github.com/unfoldingWord-dev/translationCore
    branches: [release-v*]
- name: concourse
  type: git
  source:
    uri: https://github.com/unfoldingWord-dev/concourse-pipeline
    branch: master
- name: prs-to-develop
  type: pull-request
  source:
    access_token: ((github-token))
    private_key: ((github-private-key))
    repo: unfoldingWord-dev/translationCore
    base: develop
    ci_skip: true
    authorship_restriction: true
- name: upload
  type: s3-folder
  source:
    bucket: tc-builds.door43.org
    regexp: ([^/]+)\/translationCore-(.*)-(.*)-(?P<version>.*)\.(.*)
    access_key_id: ((aws-access-id))
    secret_access_key: ((aws-secret-key))
    region_name: us-west-2
    sync: false
    options:
      - "--exclude '*'"
      - "--recursive"
      - "--include 'build/*'"
      - "--acl 'public-read'"
# - name: upload
#   type: s3
#   source:
#     bucket: tc-builds.door43.org
#     regexp: ([^/]+)\/translationCore-(.*)-(.*)-(?P<version>.*)\.(.*)
#     access_key_id: ((aws-access-id))
#     secret_access_key: ((aws-secret-key))
#     region_name: us-west-2
- name: upload-index
  type: s3
  source:
    bucket: tc-builds.door43.org
    regexp: (.*).html
    access_key_id: ((aws-access-id))
    secret_access_key: ((aws-secret-key))
    region_name: us-west-2

jobs:

# test release branches
- name: test-release
  serial: true
  public: false
  plan:
    - get: concourse
    - get: code-base
      resource: release-branch
      params: {depth: 100}
      trigger: true
      version: every
    - *install-deps
    - *test-code
    - put: upload-index
      params:
        file: concourse/assets/index.html
        acl: public-read
        content_type: text/html

# build release branches
- name: build-release
  serial: true
  public: false
  plan:
  - get: code-base
    resource: release-branch
    params: {depth: 100}
    trigger: true
    passed:
      - test-release
  - get: concourse
  - task: record source branch
    file: concourse/tasks/add-build-comment.yml
    params:
      text: "From the `{BRANCH}` branch:"
  - do:
    - *install-deps
    - *build-linux
    - *build-macos
    - *build-windows
    on_failure:
      do:
      - task: record failure
        file: concourse/tasks/add-build-comment.yml
        params:
          text: "Some builds failed"
      - put: notify
        params:
          text_file: build_meta/notification.txt
    on_success:
      put: notify
      params:
        text_file: build_meta/notification.txt

# test develop branch
- name: test-develop
  serial: true
  public: false
  plan:
  - get: concourse
  - get: code-base
    resource: develop-branch
    params: {depth: 100}
    trigger: true
    version: latest
  - *install-deps
  - *test-code
  - put: upload-index
    params:
      file: concourse/assets/index.html
      acl: public-read
      content_type: text/html

# build develop branch
- name: build-develop
  serial: false
  max_in_flight: 2
  public: false
  plan:
  - get: code-base
    resource: develop-branch
    params: {depth: 100}
    trigger: true
    passed:
      - test-develop
  - get: concourse
  - task: record source branch
    file: concourse/tasks/add-build-comment.yml
    params:
      text: "From the `{BRANCH}` branch:"
  - do:
    - *install-deps
    - *build-linux
    - *build-macos
    - *build-windows
    on_failure:
      do:
      - task: record failure
        file: concourse/tasks/add-build-comment.yml
        params:
          text: "Some builds failed"
      - put: notify
        params:
          text_file: build_meta/notification.txt
    on_success:
      put: notify
      params:
        text_file: build_meta/notification.txt

# test pull requests
- name: test-pr
  public: false
  serial: true
  plan:
  - get: code-base
    resource: prs-to-develop
    params: {depth: 100}
    trigger: true
    version: every
  - get: concourse
  - do:
    - put: prs-to-develop
      params:
        path: code-base
        context: unit-tests
        status: pending
    - *install-deps
    - *test-code
    on_success:
      put: prs-to-develop
      params:
        path: code-base
        context: unit-tests
        status: success

    on_failure:
      put: prs-to-develop
      params:
        path: code-base
        context: unit-tests
        status: failure
  - put: upload-index
    params:
      file: concourse/assets/index.html
      acl: public-read
      content_type: text/html

# build pull request
- name: build-pr
  public: false
  serial: true
  plan:
  - get: code-base
    resource: prs-to-develop
    params: {depth: 100}
    trigger: true
    version: every
    passed:
      - test-pr
  - get: concourse
  - do:
    - put: prs-to-develop
      params:
        path: code-base
        context: build
        status: pending
    - *install-deps
    - *build-linux
    - *build-macos
    - *build-windows
    on_failure:
      do:
      - task: record failure
        file: concourse/tasks/add-build-comment.yml
        params:
          text: "Some builds failed"
      - put: prs-to-develop
        params:
          path: code-base
          context: build
          comment: build_meta/comment.md
          status: failure
    on_success:
      put: prs-to-develop
      params:
        path: code-base
        context: build
        comment: build_meta/comment.md
        status: success
