
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse
- name: build_meta
  path: input_meta
  optional: true

outputs:
- name: build_meta

params:
  text:

run:
  path: concourse/scripts/run-add-build-comment.sh
