
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: neutrinog/concourse-tasks

inputs:
- name: concourse
- name: code-base

outputs:
- name: code-with-dependencies

run:
  path: concourse/scripts/run-install-deps.sh
